services:
  gateway:
    build: ./gateway
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - SESSION_SECRET=${SESSION_SECRET}
      - FRONTEND_ORIGIN=http://localhost:5173
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/gateway_db
      - SERVICE_CATALOG_URL=http://catalog:4001
      - SERVICE_ANALYTICS_URL=http://analytics:4002
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: proj_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: proj
      POSTGRES_PASSWORD: proj
      POSTGRES_DB: proj
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: 